firstPage = """
# 标题： 基于全文取一个标题
例子：基于机器学习的通信网络优化模型研究
摘要
第一段：背景
大约100字

每个问题都需要按照下面类似的单独撰写成一段'\n'，不要分点叙述。
针对问题几，根据问题几回答，使用到什么模型，如何去构建该模型，做了什么工作，得到什么结果，一些具体的数值
每段大约170字

最后一段：总结敏感性分析使用和效果，结论。
大约150字

关键词： 用到的模型等，关键词大约4/5个，没有标号
例子：机器学习  优化算法  信号处理  深度学习

参考下面的问题,模型的建立与求解，按照上面模板和要求完成 标题，摘要，关键字的撰写

{问题}
{模型的建立与求解}
"""
RepeatQues = """
# 一、问题重述
## 1.1 问题背景
查询文献
根据题目总结问题背景（查询文献）
格式：一段话
大约160字
## 1.2 问题重述
参考模板如下
本文基于以上信息建立数学模型来解决以下问题。
分点叙述

**参考下面的题目要求和问题，按照上面模板和要求完成 **问题重述中的问题背景和问题重述**

{题目}
"""
analysisQues = """
# 二、问题分析
## 2.1 问题一分析
与题目相关的主要方法有：XXXX、XXXX等
对本问题的分析.........
大约100字
## 2.2 问题二分析
与题目相关的主要方法有：XXXX、XXXX等
对本问题的分析.........
大约100字
## 2.3 问题三分析
与题目相关的主要方法有：XXXX、XXXX等
对本问题的分析.........
大约100字
## 2.4 总体技术路线
请用mermaid格式绘制一个技术路线图（flowchart），说明全篇的技术路线

**分析遵循上面的格式，如果只有1个问题只需要写问题一一个的分析，如果存在更多问题相应增加分析**

**参考下面的题目要求和分析，按照上面模板和要求完成 **问题分析**

{题目}
{分析}
"""
assumption = """
# 三、 模型假设

| 编号 | 假设内容 |
| :--- | :--- |
| 1 | 假设...  |
| 2 | 假设... |
| 3 | 假设... |
| 4 | 假设... |

(3~5个假设，华为杯侧重工程与算法优化)

**按照上面表格的格式，根据{题目}，完成模型假设部分**
"""
sign = """
# 四、 符号说明

| 符号 | 说明 | 单位 |
| :--- | :--- | :--- |
| \\(X\\) | ... | ... |
| \\(Y\\) | ... | ... |
| \\(Z\\) | ... | ... |

(至少6个符号)

**按照上面表格的格式，根据{题目}补充数据，完成符号说明部分**
"""
core = """
# 五、 模型的建立与求解

{问题分析}
{问题模型建立与求解}

"""
coreQues = """
## 5.{num} 问题{num}的模型建立与求解

### 5.{num}.1 问题{num}分析
是问题{num}的进一步分析

### 5.{num}.2 数据预处理
描述如何处理数据，华为杯题目常涉及大规模数据处理

### 5.{num}.3 模型建立
模型公式如公式（{公式编号}）所示，可使用`$$...$$`进行公式渲染
$$...$$
（1）

说明模型建立的内容

### 5.{num}.4 模型求解与算法设计
使用什么算法/求解器，可给出伪代码或算法流程

首先，根据前面问题分析进行模型的求解

绘制对应图像进行可视化分析，可以使用python，请确保matplotlib能渲染中文

图像分析

**参考下面的题目和分析，按照上面模板和要求完成 **问题{num}的模型建立与求解**

{ques}
{analysis}
"""
sensitivity = """
# 六、 模型评价

## 6.1 模型优点
1. ...
2. ...
3. ...

## 6.2 模型缺点
1. ...
2. ...
3. ...

## 6.3 模型改进
经过稍加改造，模型便能推广到更多应用场景...
(应用场景，以及改进方案)
"""
