"""写作手 Agent 模块，负责基于建模结果撰写学术论文。"""

import asyncio
from app.core.agents.agent import Agent
from app.core.llm.llm import LLM
from app.core.prompts import get_writer_prompt
from app.schemas.enums import CompTemplate, FormatOutPut
from app.config.setting import ApiType
from app.tools.openalex_scholar import OpenAlexScholar
from app.utils.log_util import logger
from app.services.redis_manager import redis_manager
from app.schemas.response import SystemMessage, WriterMessage
import json
import re
from app.core.functions import writer_tools, writer_tools_anthropic
from app.schemas.A2A import WriterResponse
from typing import Optional


class WriterAgent(Agent):
    """写作手 Agent，基于建模和代码执行结果撰写竞赛论文。"""
    def __init__(
        self,
        task_id: str,
        model: LLM,
        comp_template: CompTemplate = CompTemplate.CHINA,
        format_output: FormatOutPut = FormatOutPut.Markdown,
        scholar: OpenAlexScholar | None = None,
        context_window: int = 128000,
        cancel_event: asyncio.Event | None = None,
        lang: str = "zh",
    ) -> None:
        super().__init__(task_id, model, context_window, cancel_event=cancel_event)
        self.format_out_put = format_output
        self.comp_template = comp_template
        self.scholar = scholar
        self.is_first_run = True
        self.lang = lang
        self.system_prompt = get_writer_prompt(format_output, lang)
        self.available_images: list[str] = []
        # Cross-section footnote tracking: {footnote_number: citation_text}
        self.all_footnotes: dict[int, str] = {}
        self._next_footnote_number = 1

    def _extract_footnotes(self, text: str) -> tuple[str, dict[int, str]]:
        """Extract citation footnotes {[^N]: citation text} from text.

        Returns (cleaned_text, {number: citation_text}).
        """
        footnotes: dict[int, str] = {}
        # Match {[^N]: citation text} with optional trailing punctuation
        pattern = r"\{\[\^(\d+)\]:\s*(.*?)\}"

        def _replace(m: re.Match) -> str:
            num = int(m.group(1))
            citation = m.group(2).strip().rstrip(".")
            footnotes[num] = citation
            # Return just the footnote marker for now
            return f"[^{num}]"

        cleaned = re.sub(pattern, _replace, text)
        return cleaned, footnotes

    async def run(
        self,
        prompt: str,
        available_images: list[str] | None = None,
        sub_title: str | None = None,
    ) -> WriterResponse:
        """
        执行写作任务
        Args:
            prompt: 写作提示
            available_images: 可用的图片相对路径列表
            sub_title: 子任务标题
        """
        logger.info(f"subtitle是:{sub_title}")

        api_type = self.model.api_type
        tools = writer_tools_anthropic if api_type == ApiType.ANTHROPIC else writer_tools

        if self.is_first_run:
            self.is_first_run = False
            await self.append_chat_history(
                {"role": "system", "content": self.system_prompt}
            )

        if available_images:
            self.available_images = available_images
            image_lines = "\n".join(
                [f"- ![{img}]({img})" for img in available_images]
            )
            img_heading = "【必须插入的图片列表】" if self.lang == "zh" else "[Mandatory Image List]"
            img_instruction = (
                "以下图片是代码手生成的，你必须在论文相关段落后用 Markdown 格式逐一插入："
                if self.lang == "zh"
                else "These images were generated by the coder agent. You MUST insert each one after the relevant paragraph using Markdown format:"
            )
            img_format = (
                "插入格式为独占一行的 ![描述](文件名)，每张图片后需配3行以上的分析解读。"
                if self.lang == "zh"
                else "Format: ![description](filename) on its own line, followed by at least 3 lines of analysis."
            )
            image_prompt = (
                f"\n\n{img_heading}\n"
                f"{img_instruction}\n"
                f"{image_lines}\n"
                f"{img_format}\n"
            )
            prompt = prompt + image_prompt

        logger.info(f"{self.__class__.__name__}:开始:执行对话")

        await self.append_chat_history({"role": "user", "content": prompt})

        response = await self._chat(
            history=self.chat_history,
            tools=tools,
            tool_choice="auto",
            agent_name=self.__class__.__name__,
            sub_title=sub_title,
        )

        response_content: str = ""
        tool_footnotes: list[tuple[str, str]] = []

        if response.tool_calls:
            tool_call = response.tool_calls[0]
            tool_id = tool_call.id
            if tool_call.name == "search_papers":
                tool_msg = (
                    f"写作手调用{tool_call.name}工具"
                    if self.lang == "zh"
                    else f"Writer called tool: {tool_call.name}"
                )
                await redis_manager.publish_message(
                    self.task_id,
                    SystemMessage(content=tool_msg),
                )

                query = json.loads(tool_call.arguments)["query"]

                await redis_manager.publish_message(
                    self.task_id,
                    WriterMessage(content=query),
                )

                assistant_msg: dict = {"role": "assistant", "content": response.content}
                if response.reasoning_content:
                    assistant_msg["reasoning_content"] = response.reasoning_content
                if response.tool_calls:
                    assistant_msg["tool_calls"] = [
                        {
                            "id": tc.id,
                            "type": "function",
                            "function": {"name": tc.name, "arguments": tc.arguments},
                        }
                        for tc in response.tool_calls
                    ]
                await self.append_chat_history(assistant_msg)

                try:
                    assert self.scholar is not None, "scholar 未初始化"
                    papers = await self.scholar.search_papers(query)
                except Exception as e:
                    error_msg = f"搜索文献失败: {str(e)}"
                    logger.error(error_msg)
                    return WriterResponse(
                        response_content=error_msg, footnotes=tool_footnotes
                    )

                assert self.scholar is not None
                papers_str = self.scholar.papers_to_str(papers)
                await self.append_chat_history(
                    {
                        "role": "tool",
                        "content": papers_str,
                        "tool_call_id": tool_id,
                        "name": "search_papers",
                    }
                )

                # Pass the formatted papers for the writer to cite
                citation_context = (
                    f"\n\n以下文献可用于引用，请使用 {{[^N]: citation info}} 格式引用：\n{papers_str}"
                    if self.lang == "zh"
                    else f"\n\nThe following papers are available for citations. Use {{[^N]: citation info}} format:\n{papers_str}"
                )
                await self.append_chat_history({"role": "user", "content": citation_context})

                next_response = await self._chat(
                    history=self.chat_history,
                    tools=tools,
                    tool_choice="auto",
                    agent_name=self.__class__.__name__,
                    sub_title=sub_title,
                )
                response_content = next_response.content or ""
        else:
            response_content = response.content or ""

        self.chat_history.append(
            {"role": "assistant", "content": response_content, "reasoning_content": response.reasoning_content}
            if response.reasoning_content
            else {"role": "assistant", "content": response_content}
        )

        # Extract footnotes from the response
        cleaned_text, section_footnotes = self._extract_footnotes(response_content)

        # Merge section footnotes into global tracking, renumbering as needed
        for num, citation in sorted(section_footnotes.items()):
            # Check if this citation already exists
            existing_num = None
            for en, ec in self.all_footnotes.items():
                if ec == citation:
                    existing_num = en
                    break
            if existing_num is not None:
                # Replace [^num] with [^existing_num] in cleaned_text
                cleaned_text = cleaned_text.replace(f"[^{num}]", f"[^{existing_num}]")
            else:
                # Assign a new sequential number
                new_num = self._next_footnote_number
                self._next_footnote_number += 1
                self.all_footnotes[new_num] = citation
                cleaned_text = cleaned_text.replace(f"[^{num}]", f"[^{new_num}]")

        # Build footnotes list for WriterResponse
        sorted_footnotes = sorted(self.all_footnotes.items(), key=lambda x: x[0])
        footnotes_resp = [(str(num), content) for num, content in sorted_footnotes]

        logger.info(f"{self.__class__.__name__}:完成:执行对话")
        return WriterResponse(response_content=cleaned_text, footnotes=footnotes_resp)

    async def summarize(self) -> str:
        """总结对话内容，生成任务执行摘要。"""
        try:
            summary_prompt = "请简单总结以上完成什么任务取得什么结果:" if self.lang == "zh" else "Briefly summarize what tasks were completed and what results were achieved:"
            await self.append_chat_history(
                {"role": "user", "content": summary_prompt}
            )
            response = await self._chat(
                history=self.chat_history, agent_name=self.__class__.__name__
            )
            response_content = response.content or ""
            summary_msg: dict = {"role": "assistant", "content": response_content}
            if response.reasoning_content:
                summary_msg["reasoning_content"] = response.reasoning_content
            await self.append_chat_history(summary_msg)
            return response_content
        except Exception as e:
            logger.error(f"总结生成失败: {str(e)}")
            fallback_zh = "由于网络原因无法生成详细总结，但已完成主要任务处理。"
            fallback_en = "Unable to generate detailed summary due to network issues, but main tasks have been completed."
            return fallback_en if self.lang == "en" else fallback_zh
